source "https://supermarket.getchef.com"

#metadata

cookbook 'selinux'
cookbook 'python'
cookbook 'mysql'
cookbook 'iptables'
cookbook 'database'
cookbook 'openstack-sample', git: 'https://github.com/josug-book1-materials/cookbook-openstack-sample.git'
